// examples/vue/src/components/LinkToRepository.vue
<template>
    <a
        :style="style"
        href="https://github.com/hmsk/vite-plugin-markdown"
        target="_blank"
    >
        <slot />
    </a>
</template>

<script>
export default {
    name: 'LinkToRepository',
    props: {
        color: String,
    },
    computed: {
        style() {
            return {
                color: this.color,
            };
        },
    },
};
</script>

// examples/react/src/LinkToRepository.jsx
import React from 'react';

export default function LinkToRepository({ color, children }) {
    const style = { color: color || '#eee' };
    return (
        <a
            href="https://github.com/hmsk/vite-plugin-markdown"
            target="_blank"
            style={style}
        >
            {children}
        </a>
    );
}
